FROM ruby:2.6.3

RUN apt-get update -qq 
RUN apt-get install -y build-essential libpq-dev nodejs


RUN mkdir /fireflyapp
WORKDIR /fireflyapp

ADD Gemfile /fireflyapp/Gemfile
ADD Gemfile.lock /fireflyapp/Gemfile.lock


RUN  bundle install

ADD . /fireflyapp




